version: '3.8'

services:
  db:
    image: mysql:8.0-oracle
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3309:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  sidekiq:
    build: ./
    command: bundle exec sidekiq
    restart: always
    depends_on:
      - redis
      - elasticsearch
      - db
    volumes:
      - .:/app
      - app-storage:/app/storage
    environment:
      - REDIS_URL=${REDIS_URL}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  web:
    build: ./ 
    entrypoint: docker-entrypoint.sh
    command: bundle exec rails s -b '0.0.0.0'
    restart: always
    ports:
      - '3005:3000'
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=${REDIS_URL}
    volumes:
      - .:/app
      - app-storage:/app/storage
    depends_on:
      - db
      - redis
      - sidekiq
      - elasticsearch
    stdin_open: true
    tty: true 

volumes:
  mysql-data: {}
  app-storage: {}
  es-data: {}
  redis-data: {}
